alias sw='cd ~/<%= node['workspace_directory'] %>/sprout-wrap'
alias sprout='cd ~/<%= node['workspace_directory'] %>/sprout'
alias chefrepo='cd ~/<%= node['workspace_directory'] %>/chef-repo'
alias chefds='cd ~/<%= node['workspace_directory'] %>/chef-config-data-science'
alias mci='cd ~/<%= node['workspace_directory'] %>/mc-intelligence'
alias poptarts='cd ~/<%= node['workspace_directory'] %>/datasci-poptarts'
alias poptartsc='cd ~/<%= node['workspace_directory'] %>/datasci-poptarts-cookbook'
alias simit='cd ~/<%= node['workspace_directory'] %>/datasci-simit && source ~/.virtualenv/simit/bin/activate'
alias simitc='cd ~/<%= node['workspace_directory'] %>/datasci-simit-cookbook'
alias contl='cd ~/<%= node['workspace_directory'] %>/datasci-continental'
alias contlc='cd ~/<%= node['workspace_directory'] %>/datasci-continental-cookbook'
